Adds Instance Type r5.16xlarge and r5.8xlarge
engineyard/fog-aws pull request #17
Opened 2020-04-20 11:55 UTC by rupikakapoor

2020-06-30 09:38 UTC, paulasaurus requested changes
Spelling error on line 389. Also, looks like 389 and 469 should be named "Twenty Four Extra Large" in line with the existing M5.24XL instance.

2020-06-30 09:49 UTC, rupikakapoor commented
@paulasaurus corrected now.

2020-06-30 09:56 UTC, paulasaurus approved these changes

2020-08-31 14:15 UTC, javlonsodikov approved these changes

2020-08-31 14:16 UTC, merged